prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false
hub:
  resources: # should fill up single node to near capacity
    requests:
      cpu: 1
      memory: 2G
    limits:
      cpu: 2
      memory: 4G
  #db: # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1244
  #  upgrade: true
scheduling:
  userPods:
    nodeAffinity:
      matchNodePurpose: require
singleuser:
  cloudMetadata: # taken care of by eksctl node configuration
    enabled: true
  defaultUrl: "/lab"
  serviceAccountName: jovyan
  storage:
    capacity: 100Gi
  startTimeout: 600
  cpu:
    limit: 4
    guarantee: 3
  memory:
    limit: 16G
    guarantee: 14G
  profileList:
    - display_name: "Base-notebook (m5.2xlarge | 4 cores, 16Gb)"
      description: "latest base-notebook from pangeo-stacks"
      default: True
      kubespawner_override:
        image: pangeo/base-notebook:latest
    - display_name: "Pangeo-notebook (m5.2xlarge | 4 cores, 16Gb)"
      description: "latest pangeo-notebook from pangeo-stacks"
      kubespawner_override:
        image: pangeo/pangeo-notebook:latest

